INSERT INTO PISMO.OPERATIONS_TYPES
(OPERATION_TYPE_ID, DESCRIPTION, "TYPE")
VALUES(1, 'COMPRA A VISTA', 0);
INSERT INTO PISMO.OPERATIONS_TYPES
(OPERATION_TYPE_ID, DESCRIPTION, "TYPE")
VALUES(2, 'COMPRA PARCELADA', 0);
INSERT INTO PISMO.OPERATIONS_TYPES
(OPERATION_TYPE_ID, DESCRIPTION, "TYPE")
VALUES(3, 'SAQUE', 0);
INSERT INTO PISMO.OPERATIONS_TYPES
(OPERATION_TYPE_ID, DESCRIPTION, "TYPE")
VALUES(4, 'PAGAMENTO', 1);
commit;